version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: db-mieayam
      POSTGRES_USER: subrutin
      POSTGRES_PASSWORD: subrutin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      UPLOADS_DIR: /data/uploads
      APP_ENV: dev
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: mahmudiaan88@gmail.com
      SPRING_MAIL_PASSWORD: berurlcbwxtybdan
      APP_MAIL_FROM: mahmudiaan88@gmail.com
      APP_WHATSAPP_TOKEN: ${APP_WHATSAPP_TOKEN}
      APP_WHATSAPP_PHONE_NUMBER_ID: ${APP_WHATSAPP_PHONE_NUMBER_ID}
    volumes:
      - ./uploads:/data/uploads
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
